version: '3'

services:
  ui:
    container_name: app-ui
    image: 'ivaantorres/real-time-chat-app:0.1'
    ports:
      - '80:80'
      
  api:
    container_name: app-api
    build:
      context: ./
      target: prod
    ports:
      - '3000:3000'
    volumes:
      - '/usr/src/app/node_modules' # Necesario para el arranque de la app en Docker
      - '.:/usr/src/app'

  mongo:
    container_name: mongo
    image: 'mongo:5.0.6'
    ports:
      - '27017:27017'
    volumes:
      - '/c/data/db:/data/db'
    logging:
      driver: none