version: '3'

services:
  app:
    build:
      context: ./
      target: prod
    ports:
      - '3000:3000'
    container_name: app-back
    volumes:
      - '/usr/src/app/node_modules' # Necesario para el arranque de la app en Docker
      - '.:/usr/src/app'

  mongo:
    image: 'mongo:5.0.6'
    ports:
      - '27017:27017'
    container_name: mongo
    volumes:
      - '/c/data/db:/data/db'
    logging:
      driver: none