#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BLUE='\033[0;34m'
NC='\033[0m' # No Color

current_branch=`git rev-parse --abbrev-ref HEAD`
if [[ $current_branch =~ master|main|dev ]]; then
  printf "${BLUE}Running Integration Tests... (Jest) and Coverage (SonarQube)\n${NC}"
  npm run coverage
else
  printf "${BLUE}Running Integration Tests... (Jest)\n${NC}"
  npm run test:int
fi

printf "${BLUE}Deploying to Heroku...\n${NC}"
git push heroku $current_branch:master --no-verify